# Additional Ansible playbook on top of what Drupal-VM provides.
---
- hosts: all
  become: true
  tasks:

  - name: Install some tools
    apt: name={{item}} state=installed
    with_items:
      - lynx
      - jq

  - name: Avoid xdebug warnings
    copy:
      content: ""
      dest: /tmp/xdebug.log
      force: yes
      group: vagrant
      owner: vagrant
      mode: 0755
