# Additional Ansible playbook on top of what Drupal-VM provides.
---
- hosts: all
  become: true
  tasks:

  - file: path=/tmp/xdebug.log state=file owner=vagrant group=vagrant

  - name: Install some tools
    apt: name={{item}} state=installed
    with_items:
      - lynx
      - jq
